### ISSUE TITLE
Please enable environment variables for CFLAGS, LDFLAGS

### ISSUE THREAD

**Issue by C0RD** [markmoraes/jove#11]
Hello,

for hardening-purposes Debian wants to compile the binaries with some flags like
```
CFLAGS="-g -O2  -fstack-protector-strong -Wformat -Werror=format-security"
CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"
LDFLAGS="-Wl,-z,relro -Wl,-z,now"
```
the buildflags.sh-script just ignores those. 

https://wiki.debian.org/HardeningWalkthrough

**Comment by markmoraes** [comment]
Trying to get environment variables through make is messy, and I think that the conventional way to ensure that those override what is in the Makefile is to use 'make -e', or 'make VAR=val'.  

But in https://github.com/jonmacs/jove/commit/dcac38622267c088d53b3a70debbece5163fef12, buildflags.sh now uses dpkg-buildflags (if available) which I think should set what is needed for Debian hardening (I assume dpkg-buildflags, which comes from dpkg-dev, will be installed on any machine someone is using to create packages?)

**Comment by markmoraes** [comment]
@C0RD I should add that I'm having second thoughts about my 'fix' because it now requires three invocations of buildflags per 'cc' invocation, which is still very cheap (buildflags is plain shell with one call to uname, so runs extremely quick compared to cc) but the make output makes me question my idea of using `buildflags` in the first place.  I'm now wondering if it's better for me to change buildflags to a jmake wrapper script that first sets the relevant cflags, ldlibs etc and then invokes make on a vanilla makefile (revert to the older one, pre buildflags) so that anyone who wants automatic variable config can just invokve jmake, but those who prefer full manual control of all variables can invoke make directly with the variables on the command line, or edit the Makefile if they're truly old-school.  Thoughts? (I can send you a patch of the proposed jmake if you want to try that)

**Comment by vixie** [comment]
markmoraes wrote on 2022-07-06 11:46:
> @C0RD ...

not cord, but...

> ... I'm now wondering if it's better for me to change 
> buildflags to a jmake wrapper script that first sets the relevant 
> cflags, ldlibs etc and then invokes make on a vanilla makefile (revert 
> to the older one, pre buildflags) so that anyone who wants automatic 
> variable config can just invokve jmake, but those who prefer full manual 
> control of all variables can invoke make directly with the variables on 
> the command line, or edit the Makefile if they're truly old-school. 

+1 to this.

-- 
P Vixie

**Comment by markmoraes** [comment]
Pushed https://github.com/jonmacs/jove/commit/da9018786dcb2e4a30f3f63ecd5081fc710d50e1 which gets rid of buildflags.sh and adds jmake.sh, seems faster/cleaner/easier-to-read. 

So jmake.sh is now 'automatic transmission' build, should work fine on Linuxes, BSD, SunOS5.  But classic 'make SYSDEFS=... TERMCAPLIB=' or 'make CPPFLAGS=... LDLIBS=...' will work (latter preferred, I expect I'll remove the older SYSDEFS, TERMCAPLIB, EXTRALIBS in some future release when all packagers have stopped using them)

**Comment by markmoraes** [comment]
Needed a small further fix to testbuild.sh (needs bzip2, surprised I didn't notice that before, may as well add dpkg-dev so the dpkg-buildflags invocations get tested).  Passed CI builds so tagged https://github.com/jonmacs/jove/commit/511187c7350f94a7ad975f66fe56e68146dde59d as 4.17.4.5

**Comment by markmoraes** [comment]
FYI did more testing (DOS, Cygwin, Windows) and found one more bug, so tagged https://github.com/jonmacs/jove/commit/061e9d2059e6ad6f542864bbb3fa7758d4269a71 as 4.17.4.6

**Comment by C0RD** [comment]
I tried to use jmake.sh as "make"-replacement, but especially the "install" target fails as it does not use the DESTDIR variable, so i can't build a package that way. 

I also couldn't manage to get the hardening Flags through the make call.

**Comment by markmoraes** [comment]
@C0RD Try either
`./jmake.sh DESTDIR=/wherever install`
or, if DESTDIR is set in the environment already,
`./jmake.sh -e install`  
or
`./jmake.sh DESTDIR=$DESTDIR install`

If you just want to use plain `make` and the environment already has the relevant variables (CPPFLAGS, CFLAGS, LDFLAGS, LDLIBS, DESTDIR) set, then
`CPPFLAGS="$CPPFLAGS -DLinux" LDLIBS="$LDLIBS -lncurses -lutil" make -e` 
should work ?

**Comment by C0RD** [comment]
I have to admit that I'm not able to get jmake.sh to  work in Debian Build System, so I tried "make" as it has worked in the last years, but even with your hints i can't get the hardening flags through so the resulting binaries  are affected.

I attach a recent Build-log. On top comes that cross building is  broken since 4.17.1.4. (see logs at: http://crossqa.debian.net/src/jove

I have a bugreport  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023583 that claims that adding "all" as a make target will make it work, but when I try that my testbuild on amd64-arch breaks. 

[jove.log](https://github.com/jonmacs/jove/files/10071278/jove.log)
[jove-broken.log](https://github.com/jonmacs/jove/files/10071314/jove-broken.log)

I hope you can make some sense of this.

**Comment by markmoraes** [comment]
Cord, please would you try the following changes to whatever sets the variables:
1. delete the CFLAGS=... line (that should get automatically set from OPTFLAGS)
2. change CPPFLAGS to CPPFLAGS="-DLinux -D_FORTIFY_SOURCE=2" (-DLinux is essential.  -Wdate-time is already in OPTFLAGS, and should stay there, I think, but if you have a specific reason to have that in CPPFLAGS, that's probably fine too)
3. add LDLIBS=-lncurses 

I also tagged https://github.com/jonmacs/jove/releases/tag/4.17.4.7 with a couple of fixes to get rid of warnings for sprintf from recover.c, and add your hardening options to testbuild.sh

**Comment by C0RD** [comment]
thank you... somehow i managed to finally switch to jmake.sh and it looks good. 
New version has been uploaded and already processed by some autobuilders... The Cross-compilers should take over in the next hours. We'll see. 

https://buildd.debian.org/status/package.php?p=jove&suite=sid
http://crossqa.debian.net/src/jove

**Comment by C0RD** [comment]
Hello, 

Looks like Cross-compiling with jmake.sh does not work. 
http://crossqa.debian.net/build/jove_4.17.4.7-1_amd64_20221211105658.log

dh_auto_build interprets environment-variables and (beside other flags it provides the correct compiler. So the advise of some cross-compiling Debian Developer is to ignore jmake.sh and go for dh_apt_build again. 

```
include /usr/share/dpkg/buildtools.mk
include /usr/share/dpkg/buildflags.mk
CPPFLAGS+=$(shell $(PKG_CONFIG) --cflags ncurses)
LDFLAGS+=$(shell $(PKG_CONFIG) --libs ncurses)
dh_auto_build -- CFLAGS=$(CLFAGS) ...

```

**Comment by helmutg** [comment]
The alternative is to make jmake.sh compatible with cross compilation. Doing so entails:
 * Make it honour the CC environment variable (upper case).
 * Make the uname output overridable somehow.
 * Make it honour the PKG_CONFIG environment variable.

(and then pass all of those for the Debian build explicitly)

**Comment by markmoraes** [comment]
@C0RD Thinking about it some more, I concur with the Debian Developer that you should avoid jmake.sh and set the right env vars for make directly, since there's a degree of care/complexity needed for native and cross build that would be too hard for jmake.sh to get right for various situations.

My intention with jmake.sh (which I'll add to its comments), is that it really isn't intended for distro maintainers, packagers or experienced sysadmins/developers.  It's mainly for a person unfamiliar with Jove building, who wants to build jove and have it 'just work' without too much understanding of the interactions with the underlying system.  So with that in mind, seems outside the scope to add much logic for cross-compilation or overrides -- I don't feel upto making it any closer to configure/autotools, nor to moving Jove to configure/autotools.

@helmutg 
* you're correct, jmake.sh should be passing CC=$cc to the make invocation, fixed (tagged 4.17.4.8 ).  It also accepts an override from $CC to the script before deducing anything from CC
* JMAKE_UNAME will now override uname;  while I'm not sure this is enough for cross-compiles, seems nice for testing the script through different paths. e.g. `JMAKE_UNAME=CYGWIN ./jmake.sh` did build
* jmake.sh isn't unsetting or overriding any PKG_CONFIG* variables, so those should pass cleanly through if already exported in the calling environment e.g. I assume you mean PKG_CONFIG_PATH ?  However, if I'm understanding the manual right, pkgconf or pkg-config will always search the system dir in addition to whatever is in PKG_CONFIG_PATH (unless --env-only is specified, and the latter only exists for pkgconf, and doesn't feel right to use in jmake.sh.  I could add JMAKE_PKGOPTS as an env var, but I feel this is pushing jmake.sh into a degree of heuristic complexity that will backfire in other situations;  I'm worried it's already too complex and backfiring!:-)

@C0RD Apologies, I've reverted the 4.17.4.5 change where I tried to deprecate SYSDEFS and OPTFLAGS (and switch to CPPFLAGS and CFLAGS).  That does not work well for normal builds on FreeBSD, long story.  Does the following work?   if you can point me at some docs and the appropriate debian Jove build config so I can test dh_auto_build myself, I can try to come up with a workable answer (it may well be that I need to clean up the Makefile variable orthogonality some more -- open to ideas there).  Also fine getting on a call to try to understand this live.

`include /usr/share/dpkg/buildtools.mk
include /usr/share/dpkg/buildflags.mk
CPPFLAGS+=$(shell $(PKG_CONFIG) --cflags ncurses)
LDLIBS+=$(shell $(PKG_CONFIG) --libs ncurses)
dh_auto_build -- OPTFLAGS=$(CFLAGS) SYSDEFS=-DLinux
`

**Comment by markmoraes** [comment]
Oops, I mean, something like:
```
include /usr/share/dpkg/buildtools.mk
include /usr/share/dpkg/buildflags.mk
CPPFLAGS+=$(shell $(PKG_CONFIG) --cflags ncurses)
LDLIBS+=$(shell $(PKG_CONFIG) --libs ncurses)
dh_auto_build -- OPTFLAGS=$(CFLAGS) SYSDEFS=-DLinux 
```

**Comment by C0RD** [comment]
[jove-4.17.4.8.log](https://github.com/jonmacs/jove/files/10252043/jove-4.17.4.8.log)
I switched back to dh_auto_build. 

It is more or less a wrapper that guesses what build-system is in use and then run it with some variables. (see https://man7.org/linux/man-pages/man1/dh_auto_build.1.html)  In our case it runs make. 

But with switching back also my old problems re-appear, I can't get around to get LDFLAGS in the call (which i need for debugging packages) and if i understand correctly the Makefile just set it to empty. I don't understand how jmake.sh gets around that. 

I usually build my packages in a chroot with pbuilder.  If you have a debianesc-system with deb-src entries in sources.list you can download and unpack it correctly with apt-get source jove. But you can also find it at https://packages.debian.org/sid/jove (right side) or for the last try with jmake.sh here: http://deb.debian.org/debian/pool/main/j/jove/jove_4.17.4.7-1.debian.tar.xz 

My current take is attached. 
[debian-rules.txt](https://github.com/jonmacs/jove/files/10251975/debian-rules.txt)

I set all kinds of flags but they are ignored and i get a vanilla gcc call like:
`cc -O -D`uname` -DJTC -Wdate-time -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -Wdate-time -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600   -c -o disp.o disp.c
`
but it should result in 
`cc -g -O2 -ffile-prefix-map=/build/jove-4.17.4.7=. -fstack-protector-strong -Wformat -Werror=format-security -DLinux -Wdate-time -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600   -c -o disp.o disp.c
`

**Comment by helmutg** [comment]
Your `override_dh_auto_build` noticeably lacks `all`. This is not implicitly added by `dh_auto_build`. Please check whether your build of `disp.c` happens during `override_dh_auto_build` or `override_dh_auto_install`. If it is the latter, it likely is due to missing `all`. Otherwise, this comment is a red herring.

**Comment by C0RD** [comment]
Ok, when adding "all" in build the cc calls are as hoped.
But then it fails in linking step.

it's in auto_build. auto_install-target isn't reached because of the linking error.

[jove-4.17.4.8.1.log](https://github.com/jonmacs/jove/files/10252838/jove-4.17.4.8.1.log)

**Comment by C0RD** [comment]
ok. I added LDLIBS and LDFLAGS to dh_auto_build and now it builds. I do some more checks and upload...

**Comment by C0RD** [comment]
all is working as hoped. Cross-Compiling too. Thank you.
