### ISSUE TITLE
Answer to the question in the "About" text

### ISSUE THREAD

**Issue by Smitix** [markmoraes/jove#21]
I came across this repository just now and it made me smile.
The Jonathan who wrote it is Jonathan Payne. 1983 is when he graduated Lincoln-Sudbury Regional High School in Massachusetts. The year after I did. He developed it while in high school. We had a PDP-11 computer thanks to Ken Olsen, the founder of Digital Equipment Corporation. DEC was headquartered in Maynard, but Ken lived in Sudbury.

**Comment by canoeberry** [comment]
Actually, I graduated in 1982. I worked at a local company called BBN, for two years, before I decided to go to college. It was during those two years that I worked on JOVE in the evenings after work. Coincidentally, today’s my birthday, and I’m turning 60, which is all rather shocking :-)

**Comment by canoeberry** [comment]
Also, the whole thing was thanks to Brian Harvey, who wrote a proposal to DEC asking them to donate a PDP 11/70 to our school. They didn’t donate it, but we got a 75% discount. So our school paid a shocking amount of money for that computer despite the discount.

it was Brian Harvey‘s vision, including the fact that he insisted we run UNIX instead of the DEC operating system. Also, the high school paid for a source license for UNIX so that we could learn how everything worked, including the kernel.

**Comment by Smitix** [comment]
Happy Birthday!  Sorry I messed up your graduation year. :-)
I guess we can wrap up this "issue".

**Comment by caseyleedom** [comment]
Happy Birthday Jonathan!  It's great to hear that you're still around.  I don't think that you're on the jovehacks email list, so I'll copy my recent note:

> I started using jove in about 1985 I think and people still ask me what the heck it is ...  I guess that's getting awfully close to 40 years and my entire career ...  I'm still working (Microsoft these days after a failed startup acquisition), but I hope to retire in 2.5 years when I hit the 4-year mark at Microsoft ... at 67 years old ... (sigh)  As the Dead said, "What a long strange trip it's been ..."

I think that the last time you and I saw each other was sometime around 1995 or so while I was at SGI.  We went out to a local Thai restaurant in Mountain View if I remember right ...

Casey

**Comment by canoeberry** [comment]
I vaguely remember that, Casey, but I will never forget driving to LA and spending a couple days with you and your friends back in 1988 (or possibly '89).

I use Sublime Text now, with a package called Emacs Pro Essentials (or something like that) which I wrote to make it enough Jove/Emacs like that I don't have to retrain my muscle memory. I have really come to love and rely on multi-cursor editing.

Time marches on. All rather astonishing, really.

**Comment by caseyleedom** [comment]
Ah, yes, I was working for UCLA in 1989.

I'm still living here in Palo Alto at the same apartment I started renting back in December 1989 when I took the job at Silicon Graphics.  I definitely should have bought a place since now, at 65, while I've diligently saved for most of my career and I have a reasonable "nest egg" built up, I can't calculate any constraints on my monthly expenses.  So I find myself probably "over saving".  But, my last failed startup was purchased by Microsoft (no big payout) and the benefits are good enough as I wind that portion of my life down, and now I'm taking classes at Stanford and studying Democracy, Autocracy, etc. and having a grand time hiking in  the hills, etc.

I think that either @markmoraes or @HughR said you'd moved to England?  Have you managed to retire yet and start working on what you want to do when you grow up (for the next stage of your life)?
